### ISSUE TITLE
Kickoff 2016 - 15:30 18th Feb, rm231 Dept of Biochemistry, University of Otago

### ISSUE THREAD

**Issue by murraycadzow** [OtagoStudyGroup/studyGroup#1]
First session of 2016

This will be an intro and discussion about the group as part of this we want to cover:
- best time for further meetings
- location
- possible sub groups

Also a bit of a hacky hour so bring along laptops and scripts and prepare to peer solve!

**Comment by murraycadzow** [comment]
Proposed for next meeting a 5x5 lightning SYSKA with at least 1 slot dedicated to git

**Comment by murraycadzow** [comment]
Mik will post a link about micro github accounts and how to get free private repos

**Comment by mikblack** [comment]
https://education.github.com/discount_requests/new

**Comment by murraycadzow** [comment]
List of topics for future meetings suggested today (in no particular order):
software carpentry (R, Git, bash)
python
biopython
Rcpp
Next generation sequencing stuff
LaTeX
plotting in R
circos plots
Julia
scientific programming paradigms
remote session (tmux/screen/ssh)
SQL
HPC (Nesi, how to setup for HPC purposes)
genome browser tracks (UCSC/ensembl)
Rmarkdown
shiny
bioconductor universe
unit testing
code review

**Comment by johnfrombluff** [comment]
Here's a start of a list of topics that I'm interested in, and may be able to present, although I'm no expert, just an enthusiastic hobbyist. So it would probably be better if someone more knowledgeable presented, if possible.

# Not on the list above
- [Google Go](https://golang.org).  Why? C-like syntax, but _very_ fast compilation, built-in support for concurrent processing via multiple cores or CPUs and network operations. Apparently many of Google's  core systems are being re-written (from C or C++) in Go.
- [TikZ/PGF](https://sourceforge.net/projects/pgf): graphics programming for LaTeX
- Best practices/paradigms for statistical simulation studies
- Emacs versus vi.  I know it's been done before, and is kinda pointless.  But it might be fun for some of us ;-)  (Bias disclosure: I use both, but only use vi for trivial editing, usually of configuration files. Emacs is virtually my OS)

# My votes for the list above
- Shiny
- HPC with/for R in the NeSI environment
- unit testing
- scientific programming paradigms
- Git, especially: 
  - common workflows (especially contributing to an established project hosted on Github)
  - pros and cons of hosting sites/companies. Alternatives to Github. [Bitbucket](https://bitbucket.org)?
