### ISSUE TITLE
Time for Future Meetings

### ISSUE THREAD

**Issue by TomKellyGenetics** [OtagoStudyGroup/studyGroup#2]
Please indicate here if you are able to attend studyGroup at a regular time on Thursdays at 3:30pm.

Not too late to move to a new time. Please suggest another time if you can't attend then or let us know when seminar's / events are on in other departments. Particularly if you weren't able to make it today, we understand there was a clash with a Pathology department retreat today. Forming multiple groups is still an option if timing or content needs differ for us.

Thanks,
Tom and the studygroup team.

**Comment by Anfileida** [comment]
Thursdays its good for me. Biochemistry seminar room also suits me best:) Thank you

**Comment by lmortimer** [comment]
Any day after 5pm works for me. Perhaps not Tuesdays because of Code Craft.

Logan

**Comment by Tahzeeb** [comment]
Thursday 3:30pm --- sound good to me :)

**Comment by Tahzeeb** [comment]
Thursday 3:30pm _ sounds good to me!

**Comment by TomKellyGenetics** [comment]
Hi Logan,

I think this will have to be during the week, we're looking to get more academics on board with this, and some won't be able to attend outside working hours due to family commitments. Keen to catch up with you guys on the dark side, alas it may have to be at the pub afterwards ;)

**Comment by lmortimer** [comment]
Sounds good Tom

**Comment by johnfrombluff** [comment]
Suits me just fine. Thanks!

**Comment by mandyphippsgreen** [comment]
I would like to come to these, but I can only attend within the hours of 9am-3pm, during the week. I have to leave at 3 to do the school kid pick up. So, I'll be low on your priority list but I couldn't attend a 330pm meeting.

**Comment by murraycadzow** [comment]
@abdulmonem you mentioned that pathology has a journal club that conflicts with the current time/day

**Comment by abdulmonem** [comment]
Thanks Murray, 
Pathology biomedical journal club is organised to occur every third Thursday of the month, between 3-4pm. Unfortunately, there are few sessions that will clash with SYSKA.
