### ISSUE TITLE
May 12, 1530-1630 Rm 315 Biochem - Intro R 

### ISSUE THREAD

**Issue by murraycadzow** [OtagoStudyGroup/studyGroup#27]
This session is going to be the foundation lesson for the coming sessions

We'll go through the [software carpentry R programming lessons](http://swcarpentry.github.io/r-novice-inflammation/) starting from lesson 1 and seeing where we get to, trying to cover all extras that often get missed in a course.

Bring a laptop with R/RStudio installed to get the most benefit

**Comment by murraycadzow** [comment]
For those who want to keep up but didn't manage to make it here is a brief summary:
Very brief intro to Rstudio environment
followed by most of [lesson 1](http://swcarpentry.github.io/r-novice-inflammation/01-starting-with-data.html)
we made it to immediately before "Challenge - Slicing (subsetting) data"

Next time will pick up where we left off

**Comment by TomKellyGenetics** [comment]
Is it possible to get an idea of how many will attend next time, particularly those joining midway? It's not too late to join, especiallyf you attended ResBaz or SWC before and want a refresher or extension on R. Would be good to know if more helpers are needed. More helpers can be arranged if numbers increase.

**Comment by AntonioAhn** [comment]
Hi. I will be attending next time :)

**Comment by btrouche** [comment]
Hi, I should be there too.
