### ISSUE TITLE
June 5x5 lightning syska - 11am 9/6/16 rm319 Biochem

### ISSUE THREAD

**Issue by murraycadzow** [OtagoStudyGroup/studyGroup#31]
Lightning SYSKA for June
note the earlier time of 11am, usual place (rm319 Biochem)

This weeks speakers are Mik, Tom, Murray, Nick, and Riku

short and sharp 5 minute talks

see you there

**Comment by TomKellyGenetics** [comment]
My topic will be: Taking Advantage of the Online Help Communities

Hopefully see some of you there!

**Comment by mikblack** [comment]
Hi all - my topic will be "Metagenes - what are they, and why do I love them?"

Plus I'll try to make some pretty pictures in R.

**Comment by rikutakei** [comment]
My topic will be on some cool tricks and tips in Vim and Vim plugins

**Comment by elizabethpermina** [comment]
the thing I've mentioned can be found here:
http://symbolhound.com
Also, for more bioinformatics-like questions (specific software tips, like "how to make tophat2 run faster") - seqanswers and BioStar are quite good. Same rules apply: RFTM, STFW, make it look like you are pulling your weight in trying to solve your problem.
