### ISSUE TITLE
Survey

### ISSUE THREAD

**Issue by murraycadzow** [OtagoStudyGroup/studyGroup#36]
I have made a survey to help us get an idea mostly about time and location for future sessions

[click here for survey](http://goo.gl/forms/DTnuAQKoNWPQ9e5z1)

Murray

**Comment by murraycadzow** [comment]
Sorry if you submitted before I changed the time question to be separate by day so multiple times could be selected could you refill in just that bit and resubmit

Thanks

**Comment by Tahzeeb** [comment]
Done :)
