### ISSUE TITLE
June Otago Software Carpentry Workshop 

### ISSUE THREAD

**Issue by murraycadzow** [OtagoStudyGroup/studyGroup#39]
Hi everyone,

if you are interested we're running a software carpentry work shop June 29,30 July 1 from 9-2:30 each day covering Unix Shell, Git, and R

if you are interested checkout 
https://mikblack.github.io/2016-06-29-Otago/

and register to attend here 
https://www.eventbrite.co.nz/e/nesi-university-of-otago-software-carpentry-workshop-tickets-26189071217

**Comment by Anfileida** [comment]
Does anyone know anything about using TwitteR2Mongo. I am having difficulties installing mondodb, can anyone help?

Thanks a lot in advance:)

Leida Dos Santos
marma950@student.otago.ac.nzmailto:marma950@student.otago.ac.nz
PhD Student
Department of Zoology
PO Box 56                            Tel.  +64 3 479 7986
Dunedin  9054                    Fax.  64 3 479 7584
University of Otago
New Zealand
IUCN SSC ASG Programme Officer
ldossantos@amphibians.org
http://www.amphibians.org/
http://www.nzfrogs.org
http://www.futureintech.org.nz/careers.cfm?profileID=1943
       0  0
      ( -- )
  /(      )/\
^^  ^^  ^^  ^^
PS: Please consider the environment before printing this E-mail
