### ISSUE TITLE
11am 5 July 16, rm319 Biochem - Functions and intro plotting in R

### ISSUE THREAD

**Issue by murraycadzow** [OtagoStudyGroup/studyGroup#40]
This session will briefly revisit the [SWC lesson for functions](http://swcarpentry.github.io/r-novice-gapminder/10-functions.html) and we'll start to incorporate plotting for data visualisation

Objectives for the session:
- Define a function that takes arguments.
- Return a value from a function.
- Test a function.
- Set default values for function arguments.
- Use control flow in a function
- Plot a scatter plot, histogram, and box plot
- Create and save multiple plots automatically

This session will be 11am on Tuesday the 5th July, which will be our new regular time slot

see you there

Murray

**Comment by murraycadzow** [comment]
https://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv

for the data

**Comment by TomKellyGenetics** [comment]
Let me know if we need "helpers" for this session. Always willing to help :)

Edit: Ops got the day wrong (assumed we'd stuck with Thursdays), sorry I was out of the dept to see an Optometrist.
