### ISSUE TITLE
11am 2 Aug - Social media analysis in R - rm319 Dept Biochemistry

### ISSUE THREAD

**Issue by murraycadzow** [OtagoStudyGroup/studyGroup#42]
This session Mik is going to run us through how to use R to analyse data from social media

as usual bring a laptop to follow along

**Comment by Anfileida** [comment]
Awesome!! Thank you  so much:):)

**Comment by murraycadzow** [comment]
Link for the lesson materials

https://github.com/mikblack/twitteR-intro
