### ISSUE TITLE
25 October 11am Room 319 Biochem - Introduction to the ChemmineR package

### ISSUE THREAD

**Issue by mikblack** [OtagoStudyGroup/studyGroup#48]
The session will provide a very basic introduction to the ChemmineR "Cheminformatics Toolkit" package for R.  I'll post the code we'll be using once I've written it, so remember to bring your laptops so you can follow along with the analysis.

**Comment by mikblack** [comment]
Link for the lesson materials:

https://github.com/mikblack/ChemmineR-intro

**Comment by elizabethpermina** [comment]
?Hi Mik,

I would really like to participate in this (as an instructor or a helper)

Cheers,

E

**Comment by murraycadzow** [comment]
Hi @elizabethpermina ,

I assume you are talking about the SWC workshop @ otago next week, if so flick an email to either Aleksandra Pawlik or David Eyers letting them know

Murray
