### ISSUE TITLE
11am 8th Nov rm319 Biochem: "Done Software Carpentry... now what?"

### ISSUE THREAD

**Issue by murraycadzow** [OtagoStudyGroup/studyGroup#49]
So you've done software/data carpentry and are thinking "that was interesting, I'd like to know more".

This meeting is to discuss what is on offer and future training so that we can keep up the momentum

Murray

**Comment by phcerdan** [comment]
Hi, Pablo's here, PhD student from Massey University, Palmerston North, I am involved in the organization of a Research Bazaar here on Feb, and I was having the same question: what's next to keep people in the loop? I was thinking about setting up a mozilla study group as a follow on, but I'll be interested in your thoughts.

I have been watching this repo just to learn about mozstudy groups, but of course, I am too far away to attend! May I ask if you can generate a bulletpoint list about the options you come up after the meeting?
Or if I can attend from here via zoom, skype, or something like that, but that's probably too much hassle to set up for you.

Cheers,
Pablo

**Comment by murraycadzow** [comment]
Hi @phcerdan,

I'll certainly be posting some sort of summary of what people would like to cover, similar to what I did on #1 earlier in the year.

The particular room we have doesn't really support remote attendance but it can be discussed if we want to try and facilitate remote attendance in the future

Murray

**Comment by phcerdan** [comment]
That's good enough for me. Thanks!

**Comment by murraycadzow** [comment]
Summary of the meeting today:

## What people want to get out of studyGroup:
- Learn 'bioinformatics'
- How to deal with 'big data'
- up-skilling
- place to ask for help
- chance to network
- stay current with tools
- refreshing of skills from SWC

## 3 areas from software carpentry:

Commandline - BASH
Language - Everyone had done SWC R so wanted to learn more R, some interest in learning python
Version control - git/github

## Key Skills Identified to develop:
1. commandline - navigation and using day to day
2. data manipulation in language of choice
3. visualisation
4. code abstraction/generalistion/re-use
5. testing - expectations going in vs coming out and automating
6. profiling - identifying where to improve
7. chaining tasks together (pipes/streams)

## Potential lessons (unordered):
- mapping data to geography in R
- more in depth of SWC R and bash lessons - esp for loops
- ggplot2
- dplyr
- running bash from within R
- into to python for programming
- intro to NeSI for researchers
- manipulating data in bash/python
- heatmap
- git/github
