### ISSUE TITLE
11am November 22 room319 Biochem: Mass Cytometry data analysis and shiny apps

### ISSUE THREAD

**Issue by NortonS1** [OtagoStudyGroup/studyGroup#50]
This will be interesting... I will attempt to run through a clustering approach to analysing Mass cytometry data in R using SCAFFOLD. 

I will also go over the use of shiny apps for personal and intra-lab use for commonly used analyses. Shiny apps can be very powerful yet user friendly tools!

Sam

**Comment by TomKellyGenetics** [comment]
For those interested in single-cell data saw this Mpath one at conference. Also has immunology applications, takes either RNA-Seq or mass/flow cytometry data.

https://github.com/JinmiaoChenLab/Mpath
