### ISSUE TITLE
11am 14th Feb rm319 Dept of Biochemistry - 5 x 5 Lightning SYSKA

### ISSUE THREAD

**Issue by murraycadzow** [OtagoStudyGroup/studyGroup#52]
First session for the year and we're going to start off with a 5x5 lightning SYSKA.
5 speakers, 5 minutes each on stuff you should know about

Topics and speakers will be confirmed shortly
If you would like to volunteer to speak that would be awesome - just let me know

Murray

**Comment by murraycadzow** [comment]
Speakers and topics for this session are:

Dave- Overleaf
Ruth - updating R and reinstalling packages
Murray - Genomic data formats
Tanya - Slack
Mik - Rmarkdown: making it Shine

**Comment by mikblack** [comment]
Link to repo for Rmarkdown/Shiny SYSKA (presentation and dashboard code):
 
https://github.com/mikblack/flexdash-syska

Note that you'll need a recent version of RStudio to enable flexdashboards.  The presentation needs to be run from within RStudio since it contains an embedded Shiny app.

**Comment by ruthtopless** [comment]
My notes:

#find the path for your library
.libPaths()

#make a list of old packages
package_df = as.data.frame(installed.packages("/Library/Frameworks/R.framework/Versions/3.3/Resources/library"))
package_list = as.character(package_df$Package)

#auto install all old packages
install.packages(package_list)

#update packages
update.packages("/Library/Frameworks/R.framework/Versions/3.3/Resources/library", ask = F)
