### ISSUE TITLE
11am 11th April rm319 Biochem - Introduction to LaTeX

### ISSUE THREAD

**Issue by murraycadzow** [OtagoStudyGroup/studyGroup#58]
Hi all,

This session Riku is going to give and introduction to LaTeX and having recently written his thesis in it, has a pretty useful example

Murray

**Comment by murraycadzow** [comment]
Here are some of the links from today's talk

Riku masters
https://github.com/rikutakei/mastersDoc/tree/master/thesis

cheat sheet
wch.github.io/latexsheet/latexsheet-a4.pdf

LaTeX wiki
https://en.wikibooks.org/wiki/LaTeX

Otago Computer Science Dept LaTeX resources including an Otago thesis template
http://www.cs.otago.ac.nz/research/resources-for-pgs/latex-resources.php

**Comment by rikutakei** [comment]
Just a quick note about my references and how to compile the document:

All of my references in the "thesis" directory (i.e. MSc.bib, MSc2.bib and MSc3.bib) are symbolic links to the .bib files in the "ref" repository:
[https://github.com/rikutakei/ref](https://github.com/rikutakei/ref)

If you decide to compile the document, you will need to make sure the MSc*.bib files are correctly sym-linked, or directly copied into the thesis directory.

For sym-link:
`rm *.bib     # remove all the sym-links in the mastersDoc/thesis directory`
`ln -s [path/to/ref/MSc.bib] [path/to/thesis/directory] # repeat this for all the .bib files`

To directly copy the bib files:
`cp [path/to/ref/MSc.bib] [path/to/thesis/directory] # repeat this for all the .bib files`

How to compile the document (on Linux/Unix terminal with LaTeX installed):
1) `cd` to the "thesis" directory
2) run `pdflatex thesis.tex` (just keep pressing enter when it stops/pauses)
3) check that the thesis.aux file was generated and run `make`
4) repeat 3 until the output doesn't complain about some weird error
