### ISSUE TITLE
Too many dimensions - dimension reduction techniques. 11am, 14 Nov, rm319 Biochem

### ISSUE THREAD

**Issue by murraycadzow** [OtagoStudyGroup/studyGroup#71]
Mik:
I’m going to talk about PCA (principal components analysis), SVD (singular value decomposition) and MDS (multi-dimensional scaling) - how they work (and how they are basically all the same thing under certain situations), how we use them for dimension reduction (including for ancestry/relatedness correction), and how we can use the rsvd package to calculate the SVD really fast.

**Comment by mikblack** [comment]
Code and commentary at: https://github.com/mikblack/msg-pca-20171114
