### ISSUE TITLE
Part 2 - Too many dimensions - dimension reduction techniques. 11am, 12Dec, rm319 Biochem

### ISSUE THREAD

**Issue by murraycadzow** [OtagoStudyGroup/studyGroup#72]
Hi everyone,

This will be the remainder of Mik's dimension reduction lesson

it will also be the last session for the year

Murray

**Comment by mikblack** [comment]
Link to this week's material: https://github.com/mikblack/msg-pca-20171212

Rumour has it that there might be pizza...

**Comment by mandyphippsgreen** [comment]
?pizza has been ordered

________________________________
