### ISSUE TITLE
5x5 Lightning SYSKA - 15:30 18th Feb, rm319 Dept of Biochemistry, University of Otago

### ISSUE THREAD

**Issue by murraycadzow** [OtagoStudyGroup/studyGroup#8]
Lightning SYSKA offers a chance to listen to 5 presentations of 5 minutes duration on Shit You Should Know About

The purpose of these presentations is to get a quick overview on why the topic is worth knowing about and to establish if a more in depth lesson is wanted

This weeks topics and presenters are:
- Creating Posters in Inkscape - Tanya
- SSH for Remote Access - Riku
- Publishing preprints on bioRxiv and arXiv - James
- R and LaTeX - Tom
- Making heatmaps with heatmap3 - Anthony

Each presenter will have 5 minutes to demonstrate the awesomeness of their topic.

**Comment by theboocock** [comment]
My lessons has been uploaded if anyone was interested in reading more about pre-prints in biology, there are a number of links in the Rmd, for which the URL is given below.

https://github.com/OtagoStudyGroup/studyGroup/blob/gh-pages/lessons/SYSKA_Mar_2016/bioarxiv.Rmd
