### ISSUE TITLE
test 2 -> slack

### ISSUE THREAD

**Issue by dataknut** [OtagoStudyGroup/studyGroup#88]

**Comment by dataknut** [comment]
works

**Comment by ghost** [comment]
Hi Ben,

Is there any chance you can unsubscribe me to these emails? I can’t figure
out how to do it and am nonlonger at UoO.

Thanks!

**Comment by dataknut** [comment]
oohh. Perhaps an unfortunate side effect Murray?

**Comment by dataknut** [comment]
@AimeeBrown we think you need to 'un-watch' the repo? Then it will stop notifying you...

**Comment by ghost** [comment]
I don’t have any log in details anymore.. no worries if that’s the only way

**Comment by murraycadzow** [comment]
Hi @AimeeBrown, if you are receiving these alerts via email you should be able to reset your details. If you go to www.github.com and in the top right is sign-in, click on that and put in your email address and you can reset your password if you have forgotten it. 

Once you log in go to https://github.com/OtagoStudyGroup/studyGroup and in the top right there should be an option to unwatch

Murray
